// @ts-nocheck

// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async githubIssueState(owner: string, repo: string, number: number) : Promise<Result<GitHubIssueState, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:todo|github_issue_state", { owner, repo, number }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async githubIssueDetail(owner: string, repo: string, number: number) : Promise<Result<Issue, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:todo|github_issue_detail", { owner, repo, number }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async githubIssueComments(owner: string, repo: string, number: number) : Promise<Result<IssueComment[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:todo|github_issue_comments", { owner, repo, number }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

export type GitHubIssueState = "Open" | "Closed" | "Merged"
export type Issue = { id: number; number: number; title: string; body?: string | null; state: string; state_reason?: string | null; html_url: string; url: string; user?: User | null; assignees?: User[] | null; labels?: Label[] | null; milestone?: Milestone | null; pull_request?: IssuePullRequest | null; locked?: boolean | null; comments?: number | null; created_at: string; updated_at: string; closed_at?: string | null; closed_by?: User | null; draft?: boolean | null }
export type IssueComment = { id: number; body?: string | null; user?: User | null; created_at: string; updated_at: string; html_url: string }
export type IssuePullRequest = { url?: string | null; html_url?: string | null; diff_url?: string | null; patch_url?: string | null; merged_at?: string | null }
export type Label = { id: number; name: string; color?: string | null; description?: string | null }
export type Milestone = { id: number; number: number; title: string; description?: string | null; state: string }
export type User = { id: number; login: string; avatar_url?: string | null; html_url: string }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
