// @ts-nocheck

// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async availableProviders() : Promise<CalendarProviderType[]> {
    return await TAURI_INVOKE("plugin:calendar|available_providers");
},
async isProviderEnabled(provider: CalendarProviderType) : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:calendar|is_provider_enabled", { provider }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listConnectionIds() : Promise<Result<ProviderConnectionIds[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:calendar|list_connection_ids") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listCalendars(provider: CalendarProviderType, connectionId: string) : Promise<Result<CalendarListItem[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:calendar|list_calendars", { provider, connectionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listEvents(provider: CalendarProviderType, connectionId: string, filter: EventFilter) : Promise<Result<CalendarEvent[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:calendar|list_events", { provider, connectionId, filter }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async openCalendar(provider: CalendarProviderType) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:calendar|open_calendar", { provider }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createEvent(provider: CalendarProviderType, input: CreateEventInput) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:calendar|create_event", { provider, input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Start the browser-based Microsoft sign-in and return the authorize URL for
 * the caller to open. PKCE is handled entirely in Rust.
 */
async microsoftStartLogin() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:calendar|microsoft_start_login") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Redeem an OAuth callback URL by hand. The deep link normally completes the
 * flow on its own; this exists for builds where the custom scheme is not
 * registered, and for tests.
 */
async microsoftCompleteLogin(callbackUrl: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:calendar|microsoft_complete_login", { callbackUrl }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Forget the locally stored refresh token. Access on Microsoft's side stays
 * until the user revokes it in their account settings.
 */
async microsoftDisconnect() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:calendar|microsoft_disconnect") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async microsoftIsConnected() : Promise<boolean> {
    return await TAURI_INVOKE("plugin:calendar|microsoft_is_connected");
},
/**
 * Write one raw Microsoft Graph `calendarView` response — request URL,
 * `Preference-Applied`, and the untouched body — to a file, and return its
 * path. This is how a tenant's actual timezone behaviour gets confirmed rather
 * than assumed.
 */
async microsoftDumpRawEvents(from: string, to: string, calendarId: string | null) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:calendar|microsoft_dump_raw_events", { from, to, calendarId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/


export const events = __makeEvents__<{
calendarChangedEvent: CalendarChangedEvent,
microsoftConnectionChangedEvent: MicrosoftConnectionChangedEvent
}>({
calendarChangedEvent: "plugin:calendar:calendar-changed-event",
microsoftConnectionChangedEvent: "plugin:calendar:microsoft-connection-changed-event"
})

/** user-defined constants **/



/** user-defined types **/

export type AttendeeRole = "chair" | "required" | "optional" | "nonparticipant"
export type AttendeeStatus = "pending" | "accepted" | "tentative" | "declined"
export type CalendarChangedEvent = null
export type CalendarEvent = { provider: CalendarProviderType; 
/**
 * Unique between events. Synthesized from eventIdentifier:YYYY-MM-DD for recurring events.
 */
id: string; 
/**
 * Calendar id.
 */
calendar_id: string; 
/**
 * iCal identifier used for deduplication (calendarItemExternalIdentifier).
 */
external_id: string; title: string; description: string | null; location: string | null; url: string | null; 
/**
 * Parsed from the event notes.
 */
meeting_link: string | null; 
/**
 * ISO 8601.
 */
started_at: string; 
/**
 * ISO 8601.
 */
ended_at: string; timezone: string | null; is_all_day: boolean; 
/**
 * Apple: None | Confirmed | Tentative | Canceled -> map None to Confirmed.
 */
status: EventStatus; organizer: EventPerson | null; attendees: EventAttendee[]; has_recurrence_rules: boolean; 
/**
 * The recurrence's series_identifier, the same across all occurrences of a recurring event.
 */
recurring_event_id: string | null; 
/**
 * Raw data, as JSON.
 */
raw: string }
export type CalendarListItem = { provider: CalendarProviderType; id: string; title: string; source: string | null; color: string | null; is_primary: boolean | null; can_edit: boolean | null; raw: string }
export type CalendarProviderType = "apple" | 
/**
 * Microsoft 365 / Outlook.com, read directly from Microsoft Graph.
 */
"microsoft"
export type CreateEventInput = { calendar_tracking_id: string; title: string; started_at: string; ended_at: string; is_all_day: boolean | null; location: string | null; notes: string | null; url: string | null }
export type EventAttendee = { name: string | null; 
/**
 * Apple calendar events only provide a contact entry, which can possibly not have an email.
 */
email: string | null; 
/**
 * Apple: participant.isCurrentUser.
 */
is_current_user: boolean; 
/**
 * Apple: EKParticipantStatus (Unknown | Pending | Accepted | Declined | Tentative | Delegated | Completed | InProgress).
 * Normalize: unknown -> Pending, delegated/completed/inProgress -> Accepted.
 */
status: AttendeeStatus; 
/**
 * Apple: EKParticipantRole (Unknown | Required | Optional | Chair | NonParticipant).
 * Normalize unknown as required (see RFC 5545 3.2.16).
 */
role: AttendeeRole }
export type EventFilter = { from: string; to: string; calendar_tracking_id: string }
/**
 * Apple: {name, email, isCurrentUser, ...}.
 */
export type EventPerson = { name: string | null; 
/**
 * Apple calendar events only provide a contact entry, which can possibly not have an email.
 */
email: string | null; 
/**
 * Apple: participant.isCurrentUser.
 */
is_current_user: boolean }
export type EventStatus = "confirmed" | "tentative" | "cancelled"
/**
 * Emitted when a Microsoft sign-in finishes, since the OAuth callback arrives
 * over the OS deep link rather than as the reply to a command.
 */
export type MicrosoftConnectionChangedEvent = { connected: boolean; error: string | null }
export type ProviderConnectionIds = { provider: CalendarProviderType; connection_ids: string[] }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
